package application

import (
	"github.com/byte/scholarship-os/apps/api/internal/features/ownership"
	"github.com/go-chi/chi/v5"
)

func MountRoutes(r chi.Router, h *Handler, owners *ownership.Middleware) {
	r.Get("/applications", h.List)
	r.Post("/applications", h.Create)
	r.With(owners.Application("get application")).Get("/applications/{applicationID}", h.Get)
	r.With(owners.Application("update application")).Patch("/applications/{applicationID}", h.Update)
	r.With(owners.Application("delete application")).Delete("/applications/{applicationID}", h.Delete)
	r.With(owners.Application("get application summary")).Get("/applications/{applicationID}/summary", h.Summary)
	r.With(owners.Application("get application readiness")).Get("/applications/{applicationID}/readiness", h.Readiness)
	r.With(owners.Application("get application eligibility")).Get("/applications/{applicationID}/eligibility", h.Eligibility)
	r.With(owners.Application("list application requirements")).Get("/applications/{applicationID}/requirements", h.ListRequirements)
	r.With(owners.Application("create application requirement")).Post("/applications/{applicationID}/requirements", h.CreateRequirement)
	r.With(owners.Application("get application requirement")).Get("/applications/{applicationID}/requirements/{requirementID}", h.GetRequirement)
	r.With(owners.Application("update application requirement")).Patch("/applications/{applicationID}/requirements/{requirementID}", h.UpdateRequirement)
	r.With(owners.Application("delete application requirement")).Delete("/applications/{applicationID}/requirements/{requirementID}", h.DeleteRequirement)
	r.With(owners.Application("list requirement evidence")).Get("/applications/{applicationID}/requirements/{requirementID}/evidence", h.ListEvidence)
	r.With(owners.Application("create requirement evidence")).Post("/applications/{applicationID}/requirements/{requirementID}/evidence", h.CreateEvidence)
	r.With(owners.Application("suggest requirement evidence")).Get("/applications/{applicationID}/requirements/{requirementID}/evidence-suggestions", h.EvidenceSuggestions)
	r.With(owners.Application("list application deadlines")).Get("/applications/{applicationID}/deadlines", h.ListDeadlines)
	r.With(owners.Application("create application deadline")).Post("/applications/{applicationID}/deadlines", h.CreateDeadline)
	r.With(owners.Application("update application deadline")).Patch("/applications/{applicationID}/deadlines/{deadlineID}", h.UpdateDeadline)
	r.With(owners.Application("delete application deadline")).Delete("/applications/{applicationID}/deadlines/{deadlineID}", h.DeleteDeadline)
	r.With(owners.Application("list application funding")).Get("/applications/{applicationID}/funding", h.ListFunding)
	r.With(owners.Application("create application funding")).Post("/applications/{applicationID}/funding", h.CreateFunding)
	r.With(owners.Application("update application funding")).Patch("/applications/{applicationID}/funding/{fundingID}", h.UpdateFunding)
	r.With(owners.Application("delete application funding")).Delete("/applications/{applicationID}/funding/{fundingID}", h.DeleteFunding)
	r.With(owners.Application("list application contacts")).Get("/applications/{applicationID}/contacts", h.ListContacts)
	r.With(owners.Application("create application contact")).Post("/applications/{applicationID}/contacts", h.CreateContact)
	r.With(owners.Application("update application contact")).Patch("/applications/{applicationID}/contacts/{contactID}", h.UpdateContact)
	r.With(owners.Application("delete application contact")).Delete("/applications/{applicationID}/contacts/{contactID}", h.DeleteContact)
	r.With(owners.Application("list application supervisors")).Get("/applications/{applicationID}/supervisors", h.ListSupervisors)
	r.With(owners.Application("create application supervisor")).Post("/applications/{applicationID}/supervisors", h.CreateSupervisor)
	r.With(owners.Application("update application supervisor")).Patch("/applications/{applicationID}/supervisors/{supervisorID}", h.UpdateSupervisor)
	r.With(owners.Application("delete application supervisor")).Delete("/applications/{applicationID}/supervisors/{supervisorID}", h.DeleteSupervisor)
	r.With(owners.Application("list application URLs")).Get("/applications/{applicationID}/urls", h.ListURLs)
	r.With(owners.Application("create application URL")).Post("/applications/{applicationID}/urls", h.CreateURL)
	r.With(owners.Application("delete application URL")).Delete("/applications/{applicationID}/urls/{urlID}", h.DeleteURL)
	r.With(owners.Application("list application tasks")).Get("/applications/{applicationID}/tasks", h.ListTasks)
	r.With(owners.Application("create application task")).Post("/applications/{applicationID}/tasks", h.CreateTask)
	r.With(owners.Application("update application task")).Patch("/applications/{applicationID}/tasks/{taskID}", h.UpdateTask)
	r.With(owners.Application("delete application task")).Delete("/applications/{applicationID}/tasks/{taskID}", h.DeleteTask)
	r.With(owners.Application("complete application task")).Post("/applications/{applicationID}/tasks/{taskID}/complete", h.CompleteTask)
	r.With(owners.Application("reopen application task")).Post("/applications/{applicationID}/tasks/{taskID}/reopen", h.ReopenTask)
	r.With(owners.Application("run application research")).Post("/applications/{applicationID}/research", h.RunResearch)
	r.With(owners.Application("list application research")).Get("/applications/{applicationID}/research", h.ListResearch)
	r.With(owners.Application("mark application research stale")).Post("/applications/{applicationID}/research/mark-stale", h.MarkResearchStale)
	r.With(owners.Application("get application research run")).Get("/applications/{applicationID}/research/{runID}", h.GetResearch)
	r.With(owners.Application("list application research sources")).Get("/applications/{applicationID}/research/{runID}/sources", h.ListSources)
	r.With(owners.Application("list application research findings")).Get("/applications/{applicationID}/research/{runID}/findings", h.ListFindings)
	r.With(owners.Application("review application research finding")).Patch("/applications/{applicationID}/research/{runID}/findings/{findingID}", h.ReviewFinding)
	r.With(owners.Application("apply application research")).Post("/applications/{applicationID}/research/{runID}/apply", h.ApplyResearch)
	r.Get("/deadlines/upcoming", h.Upcoming)
	r.Get("/dashboard", h.Dashboard)
}
